# creating route table for our public subnet(s)
---
- name: Destroy route tables
  ec2_vpc_route_table:
    region: "{{ global.region}}"
    tags:
      Name: "{{ vpc.name }}-public-rt"
    vpc_id: "{{ vpc_id.vpc.id }}"
    state: absent
