---
- hosts: localhost
  tasks:
  - name: Launch an EC2 instance
    ec2:
      region: "us-west-1"
      image: "{{ lookup('env','AWS_AMI_ID') or 'ami-0dd655843c87b6930' }}"  # Ubuntu server
      instance_type: t2.micro
      wait: true
      key_name: "test_key"
      exact_count: "{{ 0 if state is defined and state == 'absent' else 1 }}"
      count_tag:
        Name: vm
      instance_tags:
        Name: vm
